# Generated by Django 4.0.1 on 2022-01-25 21:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fodder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('cost', models.FloatField()),
                ('size', models.FloatField()),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('category', models.CharField(choices=[('Buqa', 'Buqa'), ('Sigir', 'Sigir'), ('Buzoq', 'Buzoq')], max_length=30)),
                ('age', models.FloatField()),
                ('weight', models.FloatField()),
                ('sold_will', models.DateField()),
                ('sold_was', models.DateField(null=True)),
                ('sold', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Milk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liters', models.FloatField()),
                ('date', models.DateField(auto_now=True)),
                ('cow_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milk', to='main.pet')),
            ],
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=512, null=True)),
                ('about', models.TextField(blank=True, max_length=4096, null=True)),
                ('address', models.CharField(blank=True, max_length=512, null=True)),
                ('images', models.FileField(blank=True, null=True, upload_to='')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farm_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
