# Generated by Django 3.2.9 on 2021-12-01 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fodder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('cost', models.FloatField()),
                ('size', models.FloatField()),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('category', models.CharField(choices=[('Buqa', 'Buqa'), ('Sigir', 'Sigir'), ('Buzoq', 'Buzoq')], max_length=30)),
                ('age', models.FloatField()),
                ('weight', models.FloatField()),
                ('sold', models.DateField()),
                ('sold_out', models.DateField()),
                ('date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Milk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liters', models.FloatField()),
                ('date', models.DateField(auto_now=True)),
                ('cow_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milk', to='main.pet')),
            ],
        ),
    ]
