# Generated by Django 3.2.9 on 2021-12-01 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='sold',
            new_name='sold_date',
        ),
        migrations.RenameField(
            model_name='pet',
            old_name='date',
            new_name='sold_out_date',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='sold_out',
        ),
    ]
