# Generated by Django 3.2.9 on 2021-12-04 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211201_2330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='sold_out_date',
            new_name='sold_was',
        ),
        migrations.RenameField(
            model_name='pet',
            old_name='sold_date',
            new_name='sold_will',
        ),
        migrations.AddField(
            model_name='pet',
            name='sold',
            field=models.BooleanField(default=False),
        ),
    ]
